### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by Asone** [Kixunil/tonic_lnd#9]
Hi, 

First of all tonic_lnd is great and quite useful and i'd like to thank you for that !

The lib hasn't been updated on its dependencies for a while and many libs have seen some quite major releases since then, notably `tonic` and `rustls`. 

I think it could be great to update those dependencies in order to keep the lib quite up to date.  

I tried to give a shot to it, however my knowledge and understanding of both mentioned libs is way to weak to be able to propose the update myself. 

Also, my IDE has some hard time trying to give typehints due to the use of the macro `try_map_err`. 

If you ever make these updates, adding a description of the config building process would be quite useful to allow less skilled developers understand what's happening under the radar and therefore contribute to further update and improvements. 

Many thanks

**Comment by Kixunil** [comment]
Hi, thanks for the ping. I'll look at it but note that I decided MSRV should be 1.48 so if any lib breaks it I will not update it.

**Comment by Kixunil** [comment]
Sadly, those libs bumped their MSRV past 1.48 which is unacceptable here. :( I did try to look into making them compatible but it'd be quite a lot of work and convincing many people that 1.48 is important because of Debian stable. At least I did update `rustls-pemfile`.
